headersOrigin = "config"
plugins = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\Zach\\Documents\\GitHub\\JRA-zachpennington\\ar-game-template\\dist"
publishOrigin = "ui"
commandOrigin = "ui"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/manifest.webmanifest"

[headers.values]
Content-Type = "application/manifest+json"
Cache-Control = "no-cache"

[[headers]]
for = "/sw.js"

[headers.values]
Content-Type = "application/javascript; charset=utf-8"
Cache-Control = "no-cache"

[[headers]]
for = "/"

[headers.values]
Cache-Control = "no-cache"

[[headers]]
for = "/index.html"

[headers.values]
Cache-Control = "no-cache"

[[headers]]
for = "/assets/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"