// Elf skin: names, hints, and labels. Colors live in theme.css.
// Marker ids stay 1–7. kind "elf" / "cookie" are the two art slots.

export const theme = {
  id: "elf",
  brand: "elf & seek",
  title: "Elf & Seek",
  tagline: "A Brierbrook Adventure",
  description:
    "Four little elves. Three magic cookies. One real-world woodland adventure at Brierbrook Grove.",
  seekerEmoji: "🧝",
  treatEmoji: "🍪",
  finds: [
    {
      id: 4,
      kind: "elf",
      name: "Pip",
      hint: "Pip likes a place where leaves make a little shade.",
      role: "The trail keeper",
      color: "#b9d778",
      greeting:
        "You found me! The wishing tree has gone dark. A little curiosity will help it glow again.",
      riddle: "I have rings, but no fingers. What am I?",
      choices: ["A tree", "A river", "A cloud"],
      answer: 0,
      reward: "Pip is coming to the moonlight picnic.",
    },
    {
      id: 5,
      kind: "elf",
      name: "Clover",
      hint: "Clover feels at home near a pot or a garden bed.",
      role: "The garden dreamer",
      color: "#f0b899",
      greeting:
        "Shhh… I was listening to the garden grow. Can you solve my tiny mystery?",
      riddle: "What gets bigger the more you take away?",
      choices: ["A flower", "A hole", "A cookie"],
      answer: 1,
      reward: "Clover has brought a pocketful of wishes.",
    },
    {
      id: 6,
      kind: "elf",
      name: "Bramble",
      hint: "Bramble prefers a cozy place to sit and rest.",
      role: "The cookie keeper",
      color: "#c2a9e4",
      greeting:
        "I was definitely guarding the cookies. Definitely not eating them. One question first!",
      riddle: "What has a face and hands, but no arms or legs?",
      choices: ["A mushroom", "A lantern", "A clock"],
      answer: 2,
      reward: "Bramble promises to save you a cookie.",
    },
    {
      id: 7,
      kind: "elf",
      name: "Ember",
      hint: "Ember waits near a welcoming doorway, away from the road.",
      role: "The lantern lighter",
      color: "#f3c968",
      greeting:
        "Every good adventure ends with a little light. Here is your last spark of wisdom.",
      riddle: "What can you catch, but never throw?",
      choices: ["A ball", "A cold", "A leaf"],
      answer: 1,
      reward: "Ember is ready to light the wishing tree.",
    },
    {
      id: 1,
      kind: "cookie",
      name: "Moon chip",
      hint: "Look for a marker near the start of the host’s trail.",
      role: "A little moonlight",
      color: "#f3c968",
      greeting: "A golden cookie, still warm with a little woodland magic.",
      reward: "Safely tucked away for the moonlight picnic.",
    },
    {
      id: 2,
      kind: "cookie",
      name: "Berry button",
      hint: "A splash of color may be hiding this cookie’s marker.",
      role: "A little sweetness",
      color: "#eea595",
      greeting:
        "Sweet berries and a generous sprinkle of stardust. A picnic essential.",
      reward: "One more treat for the moonlight picnic.",
    },
    {
      id: 3,
      kind: "cookie",
      name: "Honey star",
      hint: "Check a low, easy-to-reach spot along the host’s trail.",
      role: "A little sunshine",
      color: "#cce1ac",
      greeting: "Someone saved the very best bite for the end of the adventure.",
      reward: "One more treat for the moonlight picnic.",
    },
  ],
};

export const copy = {
  heroLine1: "Four elves",
  heroLine2: "are ",
  heroEm: "hiding.",
  heroStory: [
    "The moonlight picnic can’t begin without them.",
    "Follow the trail, solve their riddles, and bring",
    "a little light back to Brierbrook Grove.",
  ],
  start: "Let’s find some elves",
  continue: "Continue your adventure",
  howToPlay: "How to play",
  startsAt: (street) => `Starts at ${street}.`,
  estimate: "Estimated gameplay: ",
  estimateStrong: "a relaxed 10–15 minutes",
  imagination: "EST. IN YOUR IMAGINATION",
  demoSeeking: "Finding a marker…",
  demoFound: "Pip captured",
  playPreview: "Play preview",
  pausePreview: "Pause preview",
  glance: "Your adventure at a glance",
  startsHere: "Your adventure starts here",
  seekersBlurbTitle: "4 little friends",
  seekersBlurb: "Find. Meet. Solve a riddle.",
  treatsBlurbTitle: "3 magic cookies",
  treatsBlurb: "A picnic worth searching for.",
  backToGrove: "Back to the grove",
  setupEyebrow: "BEFORE THE MAGIC BEGINS",
  setupLine1: "A tiny bit of",
  setupEm: "trail prep.",
  cameraTitle: "Meet them in your world",
  cameraBody:
    "Your rear camera brings the elves to life on the printed trail markers.",
  trailNotes: [
    "Stay on the host’s property and away from the road.",
    "Stop walking before you look through the camera.",
    "Children: bring a grown-up along for the adventure.",
  ],
  openCamera: "Open camera & begin",
  cameraNext: "We’ll ask for camera permission next.",
  privacy:
    "Privacy assured: your camera and location stay on this device.",
  checkArrive: "Check your location when you arrive.",
  findingLocation: "Finding your location…",
  checkLocation: "Check my location",
  checkAgain: "Check location again",
  fromCenter: (meters) => `About ${meters} m from the grove’s center`,
  fieldGuide: "THE FIELD GUIDE",
  helpLine1: "A little look.",
  helpEm: "magic.",
  helpLead:
    "Find four hidden elves and three cookies, then light the wishing tree for their moonlight picnic.",
  helpSteps: [
    {
      title: "Arrive at the grove",
      body: "Check in at Brierbrook. Ask your host where the safe play area begins and ends.",
    },
    {
      title: "Look for printed trail cards",
      body: "Hold your camera over the whole black square. Keep it visible for a moment to reveal a friend or cookie.",
    },
    {
      title: "Make a little discovery",
      body: "Answer each elf’s riddle. Collect cookies for the picnic.",
    },
    {
      title: "Need a hint?",
      body: "Open your field journal and choose Reveal hint.",
    },
  ],
  cardBrand: "Elf & Seek",
  cardAlt: "Printed trail card: a black square with a white block pattern",
  cardCaption: "Stop. Scan the square.",
  helpPace:
    "There’s no countdown. Stop to scan, explore at your own pace, and stay on the host’s property.",
  ready: "I’m ready to explore",
  journalEyebrow: "YOUR FIELD JOURNAL",
  journalTally: (elves, cookies) =>
    `${elves} of 4 friends · ${cookies} of 3 picnic cookies`,
  discovered: "discovered",
  stillHiding: "still hiding",
  foundBang: "Found!",
  hintPrompt: "Every good explorer needs a nudge sometimes.",
  revealHint: "Reveal hint",
  addWithoutCamera: "Add without camera",
  journalEmpty: "Choose a friend or cookie to see its story or get a hint.",
  celebrateEyebrow: "SEVEN FOR SEVEN",
  celebrateLine1: "WOW —",
  celebrateEm: "them all!",
  celebrateLead:
    "Every friend, every cookie. The wishing tree is ready to light up the grove.",
  lightTree: "Light the wishing tree",
  foundEyebrowSeeker: "A SMALL FRIEND, FOUND",
  foundEyebrowTreat: "A VERY GOOD FIND",
  riddleWrong: "Almost! Have another little think.",
  riddleWait: "A little riddle to earn a little trust.",
  invite: (name) => `Invite ${name} along`,
  tuck: "Tuck it in my basket",
  locationPaused: "Location check paused. Your discovery will wait.",
  hudSeekers: "/ 4 elves",
  hudTreats: "/ 3 cookies",
  discoveries: (n) => `${n} of 7 discoveries`,
  journalCta: "Field journal",
  journalAria: (n) => `Field journal, ${n} of 7`,
  revealing: "Revealing discovery",
  holdSteady: "A little magic… hold steady",
  frameMarker: "Frame a printed trail marker",
  keepSquare: "Keep the whole black square in view.",
  cameraWait: "The first visit may take a few seconds.",
  cameraRetryTitle1: "Let’s try",
  cameraRetryEm: "that again.",
  tryCamera: "Try camera again",
  pausedEyebrow: "ADVENTURE PAUSED",
  pausedBody: "This hunt lasts until you close the tab.",
  openingCamera: "Opening your camera…",
  addedToast: (name) => `${name} added to your journal`,
  foundTitle: (name) => `You found ${name}`,
  victoryEyebrow: "SEVEN LITTLE DISCOVERIES. ONE HAPPY GROVE.",
  victoryLine1: "You brought",
  victoryEm: "magic.",
  victoryLead:
    "The friends are together, the cookies are accounted for, and the wishing tree is glowing. Let the picnic begin.",
  titleEarned: "YOU’VE EARNED THE TITLE",
  titlePerfect: "Eagle-eyed elf whisperer",
  titleFriend: "Friend of the grove",
  statSeekers: "Friends reunited",
  statTreats: "Cookies rescued",
  statTime: "Time exploring",
  copyResults: "Copy results",
  share: "Share…",
  seeDiscoveries: "See your discoveries",
  playAgain: "Play again",
  journalModal: "Your field journal",
  restartModal: "Start a new adventure",
  restartEyebrow: "ANOTHER LITTLE ADVENTURE",
  restartLine1: "Ready for",
  restartEm: "round two?",
  restartBody:
    "This starts a fresh hunt and clears this round’s discoveries. Your host can hide the cards in new places.",
  startFresh: "Start a new adventure",
  keepDiscoveries: "Keep my discoveries",
  copiedToast: "Results copied — paste anywhere!",
  sharePerfect: "Perfect picnic — no hints, no wrong guesses!",
  shareAlmost: "still a Friend of the grove.",
  shareHints: (n) => (n === 1 ? "1 hint" : `${n} hints`),
  shareMisses: (n) => (n === 1 ? "1 miss" : `${n} misses`),
};

export const locationStatus = {
  idle: "Location not checked",
  checking: "Finding your location",
  inside: "In the grove",
  override: "In the grove",
  outside: "Outside the grove",
  boundary: "Near the edge",
  uncertain: "Location unclear",
  stale: "Location expired",
  denied: "Location off",
  unavailable: "Location not found",
  timeout: "Location not found",
  insecure: "Location unavailable",
  unsupported: "Location unavailable",
};

export const locationCopy = {
  idle: ["This hunt opens at the Brierbrook Grove.", ""],
  checking: [
    "Finding the grove…",
    "Allow location access when your browser asks. An accurate fix may take a moment.",
  ],
  inside: [
    "You’re in the grove",
    "Your location is ready. Let’s find some very small friends.",
  ],
  override: ["You’re in the grove", "This build skips the GPS check."],
  outside: [
    "The grove is a little farther away",
    "The hunt only opens at the address below. Come back when you arrive.",
  ],
  boundary: [
    "You’re near the edge",
    "GPS can’t yet place you fully inside the play area. Stay on the host’s property and check again.",
  ],
  uncertain: [
    "A clearer signal, please",
    "Your location is too approximate. Enable precise location and try a clear view of the sky.",
  ],
  stale: [
    "Let’s check your location again",
    "Your last location has expired. Check again to keep collecting.",
  ],
  denied: [
    "Location access is off",
    "Allow location for this site in your browser settings, enable Precise Location on your phone, then try again.",
  ],
  unavailable: [
    "We can’t find your location yet",
    "Check that Location Services are on, then try again outside.",
  ],
  timeout: [
    "The location check took a little long",
    "Try again with a clearer view of the sky.",
  ],
  insecure: [
    "Open the secure game link",
    "Location and camera access need HTTPS. Open the HTTPS version of this site in Safari or Chrome.",
  ],
  unsupported: [
    "Location isn’t available here",
    "Open this game in a current Safari or Chrome browser on your phone.",
  ],
};
